### ISSUE TITLE
[OpenTelemetry] actualize rr.otel config

### ISSUE THREAD

**Issue by gam6itko** [spiral/guide#703]
In [Spiral docs](https://spiral.dev/docs/advanced-telemetry/current/en#configuration) we have inconvinience with [RR docs](https://docs.roadrunner.dev/docs/logging-and-observability/otel#configuration)

I use version `2024.1.2` for me the right config is

```yaml
otel:
  resource:
    service_name: "rr_test"
    service_version: "1.0.0"
    service_namespace: "RR-Shop"
    service_instance_id: "UUID"
  insecure: true
  compress: false
  exporter: otlp
  endpoint: 127.0.0.1:4318 # NOTICE! http port not gRPC!
```

We need to correct it!
